// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './shots/geo/GeoList';
import Shot1, { compositionConfig as cfg1 } from './shots/geo/GeoWalk';
import Shot2, { compositionConfig as cfg2 } from './shots/short-walk/ShortWalkIndiaUsa';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
  { Comp: Shot1 as React.FC, config: cfg1 },
  { Comp: Shot2 as React.FC, config: cfg2 },
];
