// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './shots/geo/AndroCollide';
import Shot1, { compositionConfig as cfg1 } from './shots/geo/Antarctica';
import Shot2, { compositionConfig as cfg2 } from './shots/geo/ApophisPass';
import Shot3, { compositionConfig as cfg3 } from './shots/geo/BHFall';
import Shot4, { compositionConfig as cfg4 } from './shots/geo/BHSqueeze';
import Shot5, { compositionConfig as cfg5 } from './shots/geo/BlackHole';
import Shot6, { compositionConfig as cfg6 } from './shots/geo/DinoRock';
import Shot7, { compositionConfig as cfg7 } from './shots/geo/EarthHole';
import Shot8, { compositionConfig as cfg8 } from './shots/geo/Explore';
import Shot9, { compositionConfig as cfg9 } from './shots/geo/GalaxyHeart';
import Shot10, { compositionConfig as cfg10 } from './shots/geo/GeoDive';
import Shot11, { compositionConfig as cfg11 } from './shots/geo/GeoList';
import Shot12, { compositionConfig as cfg12 } from './shots/geo/GeoWalk';
import Shot13, { compositionConfig as cfg13 } from './shots/geo/Globe';
import Shot14, { compositionConfig as cfg14 } from './shots/geo/GlobeWalk';
import Shot15, { compositionConfig as cfg15 } from './shots/geo/IssCrash';
import Shot16, { compositionConfig as cfg16 } from './shots/geo/IssWhy';
import Shot17, { compositionConfig as cfg17 } from './shots/geo/MoonGone';
import Shot18, { compositionConfig as cfg18 } from './shots/geo/NepalFacts';
import Shot19, { compositionConfig as cfg19 } from './shots/geo/NeutronStar';
import Shot20, { compositionConfig as cfg20 } from './shots/geo/NoSpin';
import Shot21, { compositionConfig as cfg21 } from './shots/geo/ParkerSun';
import Shot22, { compositionConfig as cfg22 } from './shots/geo/RiverStory';
import Shot23, { compositionConfig as cfg23 } from './shots/geo/RiverSwim';
import Shot24, { compositionConfig as cfg24 } from './shots/geo/SunGone';
import Shot25, { compositionConfig as cfg25 } from './shots/geo/SunHole';
import Shot26, { compositionConfig as cfg26 } from './shots/geo/SunSize';
import Shot27, { compositionConfig as cfg27 } from './shots/geo/TonBH';
import Shot28, { compositionConfig as cfg28 } from './shots/geo/TrueSize';
import Shot29, { compositionConfig as cfg29 } from './shots/geo/VoyagerDay';
import Shot30, { compositionConfig as cfg30 } from './shots/geo/WormholeTime';
import Shot31, { compositionConfig as cfg31 } from './shots/geo/WormholeTravel';
import Shot32, { compositionConfig as cfg32 } from './shots/geo/Zones';
import Shot33, { compositionConfig as cfg33 } from './shots/short-walk/ShortWalkIndiaUsa';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
  { Comp: Shot1 as React.FC, config: cfg1 },
  { Comp: Shot2 as React.FC, config: cfg2 },
  { Comp: Shot3 as React.FC, config: cfg3 },
  { Comp: Shot4 as React.FC, config: cfg4 },
  { Comp: Shot5 as React.FC, config: cfg5 },
  { Comp: Shot6 as React.FC, config: cfg6 },
  { Comp: Shot7 as React.FC, config: cfg7 },
  { Comp: Shot8 as React.FC, config: cfg8 },
  { Comp: Shot9 as React.FC, config: cfg9 },
  { Comp: Shot10 as React.FC, config: cfg10 },
  { Comp: Shot11 as React.FC, config: cfg11 },
  { Comp: Shot12 as React.FC, config: cfg12 },
  { Comp: Shot13 as React.FC, config: cfg13 },
  { Comp: Shot14 as React.FC, config: cfg14 },
  { Comp: Shot15 as React.FC, config: cfg15 },
  { Comp: Shot16 as React.FC, config: cfg16 },
  { Comp: Shot17 as React.FC, config: cfg17 },
  { Comp: Shot18 as React.FC, config: cfg18 },
  { Comp: Shot19 as React.FC, config: cfg19 },
  { Comp: Shot20 as React.FC, config: cfg20 },
  { Comp: Shot21 as React.FC, config: cfg21 },
  { Comp: Shot22 as React.FC, config: cfg22 },
  { Comp: Shot23 as React.FC, config: cfg23 },
  { Comp: Shot24 as React.FC, config: cfg24 },
  { Comp: Shot25 as React.FC, config: cfg25 },
  { Comp: Shot26 as React.FC, config: cfg26 },
  { Comp: Shot27 as React.FC, config: cfg27 },
  { Comp: Shot28 as React.FC, config: cfg28 },
  { Comp: Shot29 as React.FC, config: cfg29 },
  { Comp: Shot30 as React.FC, config: cfg30 },
  { Comp: Shot31 as React.FC, config: cfg31 },
  { Comp: Shot32 as React.FC, config: cfg32 },
  { Comp: Shot33 as React.FC, config: cfg33 },
];
